name: Build and Start clicking

on: 
  schedule:
    - cron: '20 23 * * *'
  workflow_dispatch:

permissions:
  contents: write # In order to be able to update the repo sessions

jobs:
  build:
    name: Build and Start clicking
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.8'
          cache: 'pip'
      - name: Setup venv
        run: |
          python -m venv .venv
          source .venv/bin/activate
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Write the content of .env file
        run: |
          echo APP_ID=${{ secrets.APP_ID }} >> .env
          echo APP_HASH=${{ secrets.APP_HASH }} >> .env
          echo BOT_TOKEN=${{ secrets.BOT_TOKEN }} >> .env
          echo PHONE_NUMBER=${{ secrets.PHONE_NUMBER }} >> .env
      - name: Debug .env
        run: cat .env
      - name: Run script
        run: python main.py
