name: Build and Start clicking

on: 
  schedule:
    - cron: '20 0 * * *'
  workflow_dispatch:

jobs:
  build:
    name: Build and Start clicking
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup venv
        uses: getsentry/action-setup-venv@v2.1.0
        id: venv-setup
        with:
          python-version: 3.11.8
          cache-dependency-path: requirements.txt
          install-cmd: pip install -r requirements.txt
      - name: Run script
        run: |
          python main.py